# Project-wide Gradle settings.
# Paksa mesin utama Gradle menggunakan TempSQLite
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -Djava.io.tmpdir="D:/APLIKASI/EXAM_EDU_KREASI/TempSQLite" -Dorg.sqlite.tmpdir="D:/APLIKASI/EXAM_EDU_KREASI/TempSQLite" -Dorg.sqlite.tmpdir=C:\\Temp -Djava.awt.headless=true
org.gradle.parallel=false
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=false
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.paths=C:/Program Files/Android/Android Studio/jbr
org.gradle.configuration.cache=false
org.gradle.configureondemand=false

# Mengaktifkan dukungan penyelarasan 16 KB untuk Android 15+
android.bundle.enable16kPages=true

# MATIKAN worker API agar Kapt tidak membuat proses liar yang mengabaikan folder Temp
kapt.incremental.apt=false
kapt.use.worker.api=false
kapt.include.compile.classpath=false

# Paksa Kotlin Daemon menggunakan TempSQLite
kotlin.daemon.jvm.options=-Xmx2048m -Djava.io.tmpdir="D:/APLIKASI/EXAM_EDU_KREASI/TempSQLite" -Dorg.sqlite.tmpdir="D:/APLIKASI/EXAM_EDU_KREASI/TempSQLite" -Dorg.sqlite.tmpdir=C:\\Temp

# Mencegah Gradle mengunci file saat IDE sedang indexing
org.gradle.vfs.watch=false

# Room Database Verification Bypass untuk Windows
room.incremental=false
room.schemaLocation=schemas/